### ISSUE TITLE
Error in marathon_lb.py

### ISSUE THREAD

**Issue by Jugulaire** [mesosphere/marathon-lb#428]
Hi, 

When i try to run the script for installing HAproxy on marathon i got this error : 

`root@marathon-master:/home/jugu/marathon-lb# ./marathon_lb.py --marathon http://localhost:8080 --haproxy-config /etc/haproxy/haproxy.cfg --group external
marathon-lb: fetching apps
marathon-lb: GET http://localhost:8080/v2/apps?embed=apps.tasks
marathon-lb: got apps ['/web']
Traceback (most recent call last):
  File "./marathon_lb.py", line 1161, in <module>
    regenerate_config(get_apps(marathon), args.haproxy_config, args.group,
  File "./marathon_lb.py", line 876, in get_apps
    appId, servicePort, get_health_check(app, i))
  File "./marathon_lb.py", line 850, in get_health_check
    if check['portIndex'] == portIndex:
KeyError: 'portIndex'
`
I would like to know why because my marathon and mesos are running perfectly.

**Comment by brndnmtthws** [comment]
Which version of MLB is that? It looks a bit like #62 which was fixed a long time ago.

Regardless, it seems like you're running MLB in an unsupported configuration. What version of Marathon are you using?

**Comment by Jugulaire** [comment]
I use the latest version, freshly downloaded on the website of mesosphere.
I've cloned the latest version of MLB too.

**Comment by gpaul** [comment]
That seems to suggest you have specified a healthCheck for your app (presumably '/web') that does not specify a portIndex. The code on https://github.com/mesosphere/marathon-lb/blob/master/marathon_lb.py#L1211 does not provide a default value to `get` so it will raise a `KeyError` if  the key is not present.

What do you see when you hit http://localhost:8080/v2/apps?embed=apps.tasks manually?

**Comment by brndnmtthws** [comment]
Which version of Marathon?

**Comment by jkoelker** [comment]
Hi, since its been a while, I'm going to close this issue for now. If its still an issue with the latest marathon/marathon-lb, please update this issue.
